name: projeto_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.0.9
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  sizer: ^3.0.4
  uuid: ^4.5.1
  android_alarm_manager_plus: ^4.0.6
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff" # apenas para Android 8.0 ou superior
  adaptive_icon_foreground: "assets/icon/icon.png" # apenas para Android 8.0 ou superior



flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
